// Generated by Fusion2SCAD
// https://github.com/BelfrySCAD/BOSL2

include <BOSL2/std.scad>
include <BOSL2/rounding.scad>

// Set default fragment count for smooth curves
$fn = 32;

// ============================================
// Parameters (exported from Fusion 360)
// ============================================

// ============================================
// Geometry (exported from Fusion 360 features)
// ============================================

difference() {
    union() {
        // Side (1) (plane: XZ)
        multmatrix([
        [1, 0, 0, 37.5],
        [0, 0, 1, 0],
        [0, -1, 0, 12.5],
        [0, 0, 0, 1]
    ])
            cuboid([75, 25, 2.9], anchor=BOTTOM);
        // Bottom (1) (plane: XY)
        multmatrix([
        [1, 0, 0, 37.5],
        [0, 1, 0, 11],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
            cuboid([75, 22, 2.9], anchor=BOTTOM);
        // Backplate (1) (plane: YZ)
        multmatrix([
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]
    ])
            linear_extrude(height=2.9)
                polygon(points=[
                        [-8.1, 12.55],
                        [-4.7, 12.55],
                        [-4.7, 2.25],
                        [0, 2.25],
                        [0, 32.65],
                        [-12.1, 32.65],
                        [-12.1, 22.65],
                        [-8.1, 22.65],
                        [-8.1, 28.15],
                        [-4.7, 28.15],
                        [-4.7, 17.05],
                        [-12.1, 7.05],
                        [-8.1, 12.55]
                    ])
        // Support Extrude (plane: XY)
        multmatrix([
        [1, 0, 0, 70],
        [0, -1, 0, 17.5],
        [0, 0, -1, 0],
        [0, 0, 0, 1]
    ])
            cuboid([5, 5, 1.5], anchor=BOTTOM);
    }
    // Hole1
    translate([33.719, 0, 12.1817])
        rotate([90, 0, 0])
        translate([0, 0, -1.0])
        cyl(h=7, r=2.25, anchor=BOTTOM);
}